// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uciwundapajvstblkdbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjaXd1bmRhcGFqdnN0YmxrZGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODYyOTgsImV4cCI6MjA2ODM2MjI5OH0.OkaGJD_3XYmcVP5VQSgLlAxut9plnURgKDEo2O2aJ78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safe storage that falls back to memory storage if localStorage is unavailable
const safeStorage = (() => {
  try {
    // Test if localStorage is accessible
    localStorage.getItem('test');
    return localStorage;
  } catch {
    // Fallback to memory storage if localStorage is not available
    const memoryStorage: Storage = {
      length: 0,
      clear: () => {},
      getItem: () => null,
      key: () => null,
      removeItem: () => {},
      setItem: () => {},
    };
    return memoryStorage;
  }
})();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});