// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uciwundapajvstblkdbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjaXd1bmRhcGFqdnN0YmxrZGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODYyOTgsImV4cCI6MjA2ODM2MjI5OH0.OkaGJD_3XYmcVP5VQSgLlAxut9plnURgKDEo2O2aJ78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});